import { Download, FolderHeart, Heart, Search, Upload } from 'lucide-react'
import { useMemo, useRef, useState } from 'react'
import { intensityLevels } from '../../data/intensity'
import type { CreationMode, PromptCollectionRecord, SavedPromptRecord, WorkspaceBackup, WorkspaceFilters, WorkspaceSort } from '../../types'
import { filterPrompts, preferencesStorageKey, structuredPromptText } from '../../workspace/workspaceService'
import { CollectionWorkspace } from './CollectionWorkspace'
import { ConfirmDialog } from './ConfirmDialog'
import { PromptCard } from './PromptCard'
import { SavedPromptDetail } from './SavedPromptDetail'
import { TextDialog } from './TextDialog'

const creationModes: CreationMode[] = ['Build With Me', 'Shake the Box', 'I Have an Idea', 'Remix My Prompt', 'Collection Builder']
const defaultFilters: WorkspaceFilters = { production: 'All', intensity: 'All', creationMode: 'All', status: 'All', collection: 'All' }

interface WorkspaceProps {
  prompts: SavedPromptRecord[]; collections: PromptCollectionRecord[]; onBack: () => void; notify: (message: string) => void; onRemix: (prompt: SavedPromptRecord) => void
  onProduction: (prompt: SavedPromptRecord) => void
  updatePrompt: (id: string, changes: Partial<Pick<SavedPromptRecord, 'title' | 'favorite' | 'notes' | 'collectionId' | 'collectionName'>>) => void
  removePrompt: (id: string) => void; duplicatePrompt: (id: string) => SavedPromptRecord | null
  updateCollection: (id: string, changes: Partial<Pick<PromptCollectionRecord, 'name' | 'description' | 'promptIds'>>) => void
  removeCollection: (id: string) => void; duplicateCollection: (id: string) => PromptCollectionRecord | null; addToCollection: (collectionId: string, promptId: string) => void; removeFromCollection: (collectionId: string, promptId: string) => void
  backup: () => WorkspaceBackup; mergeBackup: (value: unknown) => boolean
}

function download(filename: string, content: string, type = 'text/plain') { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url) }
function safeFilename(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'prompt' }

export function SavedWorkspace(props: WorkspaceProps) {
  const [tab, setTab] = useState<'prompts' | 'favorites' | 'recent' | 'collections'>('prompts')
  const [query, setQuery] = useState('')
  const stored = (() => { try { return JSON.parse(localStorage.getItem(preferencesStorageKey) || '{}') } catch { return {} } })()
  const [filters, setFilters] = useState<WorkspaceFilters>({ ...defaultFilters, ...(stored.filters || {}) })
  const [sort, setSort] = useState<WorkspaceSort>(stored.sort || 'newest')
  const [selectedPrompt, setSelectedPrompt] = useState<string | null>(null)
  const [selectedCollection, setSelectedCollection] = useState<string | null>(null)
  const [deleteTarget, setDeleteTarget] = useState<{ type: 'prompt' | 'collection'; id: string } | null>(null)
  const [renameTarget, setRenameTarget] = useState<SavedPromptRecord | null>(null)
  const importRef = useRef<HTMLInputElement>(null)
  const activeFilters = useMemo(() => tab === 'favorites' ? { ...filters, status: 'Favorites' as const } : filters, [filters, tab])
  const visible = useMemo(() => filterPrompts(props.prompts, query, activeFilters, tab === 'recent' ? 'updated' : sort).slice(0, tab === 'recent' ? 8 : undefined), [props.prompts, query, activeFilters, sort, tab])
  const currentPrompt = props.prompts.find((item) => item.id === selectedPrompt)
  const currentCollection = props.collections.find((item) => item.id === selectedCollection)
  const remember = (nextFilters: WorkspaceFilters, nextSort = sort) => localStorage.setItem(preferencesStorageKey, JSON.stringify({ filters: nextFilters, sort: nextSort }))
  const copy = async (prompt: SavedPromptRecord) => { try { await navigator.clipboard.writeText(prompt.prompt); props.notify('Prompt copied.') } catch { props.notify('Copy was blocked by your browser.') } }
  const exportPrompt = (prompt: SavedPromptRecord, structured: boolean) => download(`${safeFilename(prompt.title)}${structured ? '-details' : ''}.txt`, structured ? structuredPromptText(prompt) : prompt.prompt)
  const exportCollection = (collection: PromptCollectionRecord) => { const members = collection.promptIds.map((id) => props.prompts.find((item) => item.id === id)).filter(Boolean) as SavedPromptRecord[]; download(`${safeFilename(collection.name)}.txt`, `GLOSS & AUDACITY™\n${collection.name}\n${collection.description}\n\n${members.map((item, index) => `${index + 1}. ${structuredPromptText(item)}`).join('\n\n')}`) }
  const handleImport = async (file?: File) => { if (!file) return; try { const parsed = JSON.parse(await file.text()); props.notify(props.mergeBackup(parsed) ? 'Workspace backup merged successfully.' : 'That backup file is not valid.') } catch { props.notify('That backup file is not valid.') } }

  if (currentPrompt) return <main className="workspace-page"><SavedPromptDetail prompt={currentPrompt} collections={props.collections} onBack={() => setSelectedPrompt(null)} onCopy={() => copy(currentPrompt)} onRemix={() => props.onRemix(currentPrompt)} onProduction={() => props.onProduction(currentPrompt)} onDuplicate={() => { props.duplicatePrompt(currentPrompt.id); props.notify('Independent copy created.') }} onExport={(structured) => exportPrompt(currentPrompt, structured)} onNotes={(notes) => props.updatePrompt(currentPrompt.id, { notes })} onDelete={() => setDeleteTarget({ type: 'prompt', id: currentPrompt.id })} onAddToCollection={(id) => props.addToCollection(id, currentPrompt.id)} /><ConfirmDialog open={Boolean(deleteTarget)} title="Delete this prompt?" body="This removes the saved record. It cannot be undone." onCancel={() => setDeleteTarget(null)} onConfirm={() => { props.removePrompt(currentPrompt.id); setDeleteTarget(null); setSelectedPrompt(null); props.notify('Prompt deleted.') }} /></main>
  if (currentCollection) { const members = currentCollection.promptIds.map((id) => props.prompts.find((item) => item.id === id)).filter(Boolean) as SavedPromptRecord[]; return <main className="workspace-page"><CollectionWorkspace collection={currentCollection} prompts={members} allPrompts={props.prompts} onBack={() => setSelectedCollection(null)} onRename={(name) => props.updateCollection(currentCollection.id, { name })} onDuplicate={() => { props.duplicateCollection(currentCollection.id); props.notify('Collection duplicated.') }} onDelete={() => setDeleteTarget({ type: 'collection', id: currentCollection.id })} onExport={() => exportCollection(currentCollection)} onCopy={copy} onOpenPrompt={(prompt) => setSelectedPrompt(prompt.id)} onRemove={(id) => props.removeFromCollection(currentCollection.id, id)} onAdd={(id) => props.addToCollection(currentCollection.id, id)} onReorder={(promptIds) => props.updateCollection(currentCollection.id, { promptIds })} /><ConfirmDialog open={Boolean(deleteTarget)} title="Delete this collection?" body="Member prompts will remain safely in Saved Prompts." onCancel={() => setDeleteTarget(null)} onConfirm={() => { props.removeCollection(currentCollection.id); setDeleteTarget(null); setSelectedCollection(null); props.notify('Collection deleted. Its prompts remain saved.') }} /></main> }

  return (
    <main className="workspace-page">
      <button className="back-button" onClick={props.onBack}>← Back to dashboard</button>
      <header className="workspace-header"><div><p className="panel-label">Your Archive</p><h1>Saved Prompts</h1><p>{props.prompts.length} prompt{props.prompts.length === 1 ? '' : 's'} · {props.collections.length} collection{props.collections.length === 1 ? '' : 's'}</p></div><div><button className="outline-button" onClick={() => download('gloss-audacity-workspace-backup.json', JSON.stringify(props.backup(), null, 2), 'application/json')}><Download size={15} /> Export Backup</button><button className="outline-button" onClick={() => importRef.current?.click()}><Upload size={15} /> Import & Merge</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={(event) => handleImport(event.target.files?.[0])} /></div></header>
      <nav className="workspace-tabs" aria-label="Saved prompt views"><button className={tab === 'prompts' ? 'active' : ''} onClick={() => setTab('prompts')}>All Prompts</button><button className={tab === 'favorites' ? 'active' : ''} onClick={() => setTab('favorites')}><Heart size={14} /> Favorites</button><button className={tab === 'recent' ? 'active' : ''} onClick={() => setTab('recent')}>Recent</button><button className={tab === 'collections' ? 'active' : ''} onClick={() => setTab('collections')}><FolderHeart size={14} /> Collections</button></nav>
      {tab !== 'collections' && <section className="panel workspace-tools"><label className="workspace-search"><span>Search saved prompts</span><div><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, concept, phrase, palette, notes…" /></div></label><div className="filter-grid"><label>Production<select value={filters.production} onChange={(e) => { const next = { ...filters, production: e.target.value as WorkspaceFilters['production'] }; setFilters(next); remember(next) }}><option>All</option><option>DTF</option><option>Sublimation</option></select></label><label>Intensity<select value={filters.intensity} onChange={(e) => { const next = { ...filters, intensity: e.target.value as WorkspaceFilters['intensity'] }; setFilters(next); remember(next) }}><option>All</option>{intensityLevels.map((level) => <option key={level}>{level}</option>)}</select></label><label>Creation Mode<select value={filters.creationMode} onChange={(e) => { const next = { ...filters, creationMode: e.target.value as WorkspaceFilters['creationMode'] }; setFilters(next); remember(next) }}><option>All</option>{creationModes.map((mode) => <option key={mode}>{mode}</option>)}</select></label><label>Collection<select value={filters.collection} onChange={(e) => { const next = { ...filters, collection: e.target.value }; setFilters(next); remember(next) }}><option>All</option>{props.collections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Sort<select value={sort} onChange={(e) => { const next = e.target.value as WorkspaceSort; setSort(next); remember(filters, next) }}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="updated">Recently Updated</option><option value="az">A–Z</option><option value="za">Z–A</option></select></label><button className="clear-filters" onClick={() => { setFilters(defaultFilters); setQuery(''); remember(defaultFilters) }}>Clear Filters</button></div></section>}
      {tab === 'collections' ? <section className="collection-grid">{props.collections.map((collection) => <button className="panel collection-card" key={collection.id} onClick={() => setSelectedCollection(collection.id)}><FolderHeart size={27} /><span>{collection.promptIds.length} prompts</span><h2>{collection.name}</h2><p>{collection.description || collection.sharedDna[0]}</p><em>Open Collection →</em></button>)}{props.collections.length === 0 && <div className="panel workspace-empty"><FolderHeart /><h2>Your collection rack is waiting.</h2><p>Create a coordinated collection in Collection Builder.</p></div>}</section>
        : <section className="prompt-card-grid">{visible.map((prompt) => <PromptCard key={prompt.id} prompt={prompt} onOpen={() => setSelectedPrompt(prompt.id)} onCopy={() => copy(prompt)} onRemix={() => props.onRemix(prompt)} onFavorite={() => props.updatePrompt(prompt.id, { favorite: !prompt.favorite })} onDuplicate={() => { props.duplicatePrompt(prompt.id); props.notify('Independent copy created.') }} onRename={() => setRenameTarget(prompt)} onDelete={() => setDeleteTarget({ type: 'prompt', id: prompt.id })} />)}{visible.length === 0 && <div className="panel workspace-empty"><Heart /><h2>{tab === 'favorites' ? 'Nothing has earned the heart yet.' : query || JSON.stringify(filters) !== JSON.stringify(defaultFilters) ? 'No prompt matched that energy.' : 'Your prompt closet is empty.'}</h2><p>{tab === 'favorites' ? 'Tap the heart on any prompt you want close at hand.' : 'Build something brilliant, then save it here.'}</p></div>}</section>}
      <ConfirmDialog open={Boolean(deleteTarget)} title="Delete this prompt?" body="This removes the saved record and its collection reference." onCancel={() => setDeleteTarget(null)} onConfirm={() => { if (deleteTarget?.type === 'prompt') props.removePrompt(deleteTarget.id); setDeleteTarget(null); props.notify('Prompt deleted.') }} />
      <TextDialog open={Boolean(renameTarget)} title="Rename Prompt" label="Prompt title" initialValue={renameTarget?.title || ''} onCancel={() => setRenameTarget(null)} onSave={(title) => { if (renameTarget) props.updatePrompt(renameTarget.id, { title }); setRenameTarget(null); props.notify('Prompt renamed.') }} />
    </main>
  )
}
