import { artStyleLibrary, effectLibrary, phraseLibrary, poseLibrary } from '../data/creativeKnowledge'
import { characterTraits } from '../data/characters'
import { compositionLibrary, describeComposition } from '../data/compositions'
import { fashionLibrary, describeFashion } from '../data/fashion'
import { paletteLibrary, describePalette } from '../data/palettes'
import { typographyLibrary, describeTypography } from '../data/typography'
import type { PromptField, PromptSelections } from '../types'
import { isRecent } from './originality'

interface CreativeWorld {
  name: string
  cues: string[]
  fashion: string[]
  typography: string[]
  palettes: string[]
  compositions: string[]
  artStyles: string[]
  poses: string[]
  expressions: string[]
  phrases: string[]
  effects: string[]
}

const worlds: CreativeWorld[] = [
  { name: 'executive power', cues: ['boss', 'career', 'work', 'ceo', 'lead', 'business', 'ambition', 'power'], fashion: ['tailored minimalism', 'monochrome power', 'executive evening', 'soft tailoring'], typography: ['monumental serif', 'engraved luxury serif', 'stacked serif monument'], palettes: ['Plum Audacity', 'Wine and Brass', 'Cobalt Espresso', 'Monochrome Cocoa'], compositions: ['low-angle hero view', 'museum poster', 'architectural doorway', 'asymmetrical fashion layout'], artStyles: ['Cinematic fashion photography translated into illustrated realism', 'Architectural blueprint drawing fused with couture rendering'], poses: ['One hand adjusting a cuff while holding direct eye contact', 'Measured step forward while fastening a blazer', 'Fingertips meeting in a composed executive pose'], expressions: ['direct commanding gaze', 'determined jaw with focused eyes', 'cool editorial detachment'], phrases: ['I KNOW WHAT I BRING', 'THE STANDARD REMAINS', 'BUILT FOR THE NEXT ROOM', 'I CAME PREPARED'], effects: ['Selective chrome edging with matte ink contrast', 'Burnished antique-metal accents against soft textile texture'] },
  { name: 'soft luxury', cues: ['soft', 'peace', 'calm', 'rest', 'ease', 'gentle', 'cozy', 'luxury'], fashion: ['quiet luxury', 'soft feminine', 'soft tailoring', 'opulent lounge'], typography: ['quiet lowercase', 'soft inflated serif', 'engraved luxury serif'], palettes: ['Soft Luxe', 'Coffee Rose', 'Powder and Ink', 'Golden Hour'], compositions: ['museum poster', 'negative-space design', 'editorial portrait crop', 'wave composition'], artStyles: ['Soft pastel beauty illustration on richly textured paper', 'Editorial watercolor with controlled translucent blooms'], poses: ['Looking down with a private smile while fabric moves around her', 'Hands clasped behind her back in a serene full-body stance', 'Quiet stillness with hands folded at the waist'], expressions: ['serene closed-eye confidence', 'subtle private smile', 'peaceful downward gaze'], phrases: ['SOFTNESS WITH STRUCTURE', 'CALM IS THE FLEX', 'EASE IS AN ACHIEVEMENT', 'PEACE IS THE PRIORITY'], effects: ['Pearlescent highlights and soft airbrushed glow', 'Soft flock texture paired with crisp satin highlights'] },
  { name: 'street statement', cues: ['street', 'urban', 'bold', 'edge', 'unbothered', 'attitude', 'cool'], fashion: ['street couture', 'elevated workwear', 'motorsport glamour', 'denim atelier'], typography: ['graffiti-inspired lettering', 'razor italic', 'torn-poster type', 'offset screen-print type'], palettes: ['Electric Monochrome', 'Neon Night', 'Indigo Denim', 'Runway Brights'], compositions: ['torn poster wall', 'corner-to-corner diagonal', 'character breaking through type', 'diagonal runway movement'], artStyles: ['Hard-flash underground fashion-zine collage', 'Kinetic comic-panel composition without copyrighted characters'], poses: ['Crouched fashion pose with strong triangular limb geometry', 'Sharp pivot captured at the peak of motion', 'Wide grounded stance with jacket held open'], expressions: ['deadpan unimpressed stare', 'wry almost-smile', 'direct commanding gaze'], phrases: ['UNBOTHERED BY OPINIONS', 'PROCEED WITH BETTER ENERGY', 'POLITE, NOT AVAILABLE', 'THE LOOK HAS A POINT'], effects: ['Distressed screen-print texture with ink brayer marks', 'Cut-vinyl geometry with clean offset shadows'] },
  { name: 'romantic dream', cues: ['romance', 'love', 'dream', 'poetic', 'tender', 'beautiful', 'floral'], fashion: ['romantic', 'romantic tailoring', 'future romantic', 'romantic prairie modernized'], typography: ['hand-painted script', 'woven ribbon script', 'satin-fold capitals', 'high-contrast serif'], palettes: ['Oxblood Blush', 'Apricot Aubergine', 'Lavender Moss', 'Mint Merlot'], compositions: ['spiral energy', 'wave composition', 'profile silhouette', 'circular composition'], artStyles: ['Soft-focus romantic cinema poster with painterly edges', 'Dreamlike magical-realism portrait with poetic scale shifts'], poses: ['One arm lifted overhead to create an elegant fashion curve', 'Turning at the waist as layered fabric spirals outward', 'Back arched subtly in a dramatic couture silhouette'], expressions: ['dreamy faraway gaze', 'tender emotional warmth', 'softly surprised delight'], phrases: ['BEAUTY IN THE IN-BETWEEN', 'TRUST THE BECOMING', 'SOFT DOES NOT MEAN SMALL', 'ROMANTICIZE THE ROUTINE'], effects: ['Watercolor blooms contained by strong ink contours', 'Nacreous pearl glow with minimal faceted sparkle'] },
  { name: 'future vision', cues: ['future', 'technology', 'innovation', 'vision', 'ahead', 'digital', 'space'], fashion: ['futuristic', 'metallic minimalism', 'future romantic', 'sculptural sportswear'], typography: ['modular geometric', 'digital editorial', 'shadow-built lettering', 'runway stencil'], palettes: ['Future Neutral', 'Silver Lilac', 'Neon Night', 'Midnight Orchid'], compositions: ['runway tunnel', 'constellation grid', 'type as architecture', 'floating platform'], artStyles: ['Afrofuturist couture illustration with original world-building', 'Airbrushed retro-futurist beauty campaign'], poses: ['Stepping upward onto an abstract platform', 'Balanced on one leg with the other creating a graphic angle', 'Low-angle runway stance with one foot advanced'], expressions: ['curious sideways glance', 'intense cinematic stare', 'cool editorial detachment'], phrases: ['FUTURE FACING', 'THE FUTURE KNOWS MY NAME', 'AHEAD OF THE MOOD', 'DESIGN THE NEXT VERSION'], effects: ['Prismatic refraction bands with disciplined black separation', 'Holographic edge flashes balanced by neutral negative space'] },
  { name: 'joy pop', cues: ['joy', 'happy', 'fun', 'play', 'celebrate', 'smile', 'party'], fashion: ['maximal print story', 'disco revival', 'mod graphic', 'artistic eclectic'], typography: ['bubbly display', 'mod bubble type', 'disco flare', 'brush-and-block pairing'], palettes: ['Papaya Plum', 'Solar Flare', 'Tropical Editorial', 'Saffron Cobalt'], compositions: ['checkerboard disruption', 'spiral energy', 'panoramic repeat', 'triptych movement'], artStyles: ['Pop-art beauty portrait with sophisticated halftone control', 'Maximalist jewel-toned poster with clear focal hierarchy'], poses: ['Open-armed celebratory movement with credible anatomy', 'Mid-laugh with shoulders turning naturally', 'Spinning skirt movement captured in a crisp silhouette'], expressions: ['joyful uninhibited laugh', 'bold open-mouthed cheer', 'warm radiant open smile'], phrases: ['JOY ON FULL DISPLAY', 'MAKE ROOM FOR DELIGHT', 'HAPPINESS HAS ENTERED THE CHAT', 'A LITTLE EXTRA JOY'], effects: ['Screen-printed gradient illusion built from printable halftone dots', 'Block-print irregularity with a perfectly crisp outer silhouette'] },
  { name: 'art-world eclectic', cues: ['art', 'creative', 'artist', 'muse', 'gallery', 'original', 'imagination'], fashion: ['art-school tailoring', 'gallery opening', 'artistic eclectic', 'knitwear art'], typography: ['brush-and-block pairing', 'cut-paper lettering', 'handwritten annotation', 'continuous-line lettering'], palettes: ['Plum Citron', 'Acid Romance', 'Peach Petrol', 'Jewel Salon'], compositions: ['scrapbook luxury', 'open-book spread', 'layered collage', 'split composition'], artStyles: ['Neo-expressionist fashion painting with disciplined mark-making', 'Fashion croquis elevated into finished mixed-media artwork'], poses: ['One hand lifted in a graceful conversational gesture', 'Asymmetric stance framed by one bent elbow and one long arm', 'Editorial crop of face, shoulders, and one expressive hand'], expressions: ['bright conversational animation', 'mischievous closed-mouth grin', 'quietly thoughtful gaze'], phrases: ['THE MUSE HAS ARRIVED', 'ART IS THE ATTITUDE', 'IDEAS DRESSED WELL', 'ORIGINAL ON PURPOSE'], effects: ['Hand-torn paper edges balanced by precise editorial rules', 'Layered translucent color fields with controlled overlap'] },
  { name: 'heritage soul', cues: ['legacy', 'heritage', 'history', 'roots', 'family', 'culture', 'soul'], fashion: ['heritage remix', '70s soul', 'academic chic', 'modern bohemian'], typography: ['arched heritage serif', 'retro groovy type', 'engraved luxury serif'], palettes: ['Deep Earth', 'Retro Muted', 'Wine and Brass', 'Indigo Denim'], compositions: ['fashion playing-card frame', 'nested silhouette', 'badge emblem', 'museum poster'], artStyles: ['Modern Harlem Renaissance-inspired elegance without imitation', 'Woodblock-inspired portrait with modern luxury color'], poses: ['Hands relaxed at her sides in a statuesque frontal portrait', 'Seated throne-like on a minimal chair without royal symbolism', 'Head tilted upward in quiet triumph'], expressions: ['proud tearful joy', 'warm radiant open smile', 'quietly thoughtful gaze'], phrases: ['ROOTED IN BRILLIANCE', 'BECOMING THE HEIRLOOM', 'LEGACY IN LIVING COLOR', 'I COME FROM GREATNESS'], effects: ['Weathered letterpress grain with a modern polished focal point', 'Enlarged embroidered stitch cues with clean connected contours'] },
  { name: 'night glamour', cues: ['night', 'glam', 'party', 'mystery', 'dark', 'sexy', 'evening'], fashion: ['dark romance', 'red-carpet sculpture', 'executive evening', 'disco revival'], typography: ['liquid chrome script', 'neo-gothic editorial', 'faceted gem type', 'high-contrast serif'], palettes: ['Midnight Orchid', 'Emerald Noir', 'Cherry Mocha', 'Ruby Ice'], compositions: ['spotlight cone', 'extreme beauty crop', 'mirror dialogue', 'profile silhouette'], artStyles: ['Vintage pulp-cover drama refined into luxury editorial art', 'Surreal editorial photomontage with believable lighting'], poses: ['One shoulder toward camera with an elongated neck line', 'Reclined diagonally across a clean architectural plane', 'Side profile in a purposeful walking motion'], expressions: ['mysterious intensity', 'intense cinematic stare', 'subtle private smile'], phrases: ['THE LIGHT KNOWS MY NAME', 'DARK, DIVINE, UNDENIABLE', 'DRESSED LIKE THE ANSWER', 'THE OUTFIT MADE THE DECISION'], effects: ['Wet lacquer highlights over deep matte color', 'Gem-like accents with dimensional gloss'] },
  { name: 'natural earth', cues: ['nature', 'earth', 'wellness', 'grounded', 'garden', 'healing', 'organic'], fashion: ['modern bohemian', 'minimal resort', 'casual elevated', 'soft tailoring'], typography: ['topographic type', 'continuous-line lettering', 'quiet lowercase'], palettes: ['Deep Earth', 'Desert Bloom', 'Golden Hour', 'Lavender Moss'], compositions: ['double exposure thoughtscape', 'nested silhouette', 'negative-space design', 'circular composition'], artStyles: ['Botanical scientific illustration fused with beauty editorial', 'Ceramic-glaze inspired portrait with fluid color pooling'], poses: ['Hands clasped behind her back in a serene full-body stance', 'Graceful kneeling pose with a long upright torso', 'Looking down with a private smile while fabric moves around her'], expressions: ['calm meditative expression', 'relieved exhale with softened features', 'serene closed-eye confidence'], phrases: ['BEAUTIFUL THINGS TAKE ROOT', 'GRACE FOR THE JOURNEY', 'WHOLE, HERE, NOW', 'ROOTED AND RADIANT'], effects: ['Ceramic glaze pooling contained inside bold graphic shapes', 'Tonal denim weave with purposeful contrast stitching'] },
  { name: 'sport motion', cues: ['sport', 'fitness', 'strong', 'move', 'run', 'dance', 'energy'], fashion: ['sporty luxe', 'sculptural sportswear', 'motorsport glamour', 'ballet-inspired streetwear'], typography: ['athletic block', 'razor italic', 'kinetic repeat type', 'runway stencil'], palettes: ['Runway Brights', 'Saffron Cobalt', 'Electric Monochrome', 'Ruby Ice'], compositions: ['diagonal runway movement', 'triptych movement', 'corner-to-corner diagonal', 'walking stride'], artStyles: ['Crisp retro screen-print illustration', 'Graphic linocut portrait with bold carved texture'], poses: ['Strong side lunge that showcases garment movement', 'Sharp pivot captured at the peak of motion', 'Joyful upward reach with the body forming a clean diagonal'], expressions: ['determined jaw with focused eyes', 'joyful uninhibited laugh', 'direct commanding gaze'], phrases: ['MY PACE. MY POWER.', 'KEEP GOING BEAUTIFULLY', 'PURPOSE IN EVERY STEP', 'LEVEL UP LOADING'], effects: ['Raised gel lettering with a clean printed illustration base', 'Sculpted puff-ink headline with a quiet flat support layer'] },
  { name: 'retro editorial', cues: ['retro', 'vintage', 'nostalgia', 'old school', 'classic'], fashion: ['retro modern', '70s soul', '80s glamour', '90s editorial'], typography: ['retro groovy type', 'disco flare', 'mod bubble type', 'offset screen-print type'], palettes: ['Retro Muted', 'Golden Hour', 'Oxblood Blush', 'Teal Copper'], compositions: ['fashion contact sheet', 'fashion playing-card frame', 'vertical stack', 'editorial portrait crop'], artStyles: ['Crisp retro screen-print illustration', 'Vintage pulp-cover drama refined into luxury editorial art'], poses: ['Three-quarter turn looking over her shoulder', 'Hands in trouser pockets with relaxed runway confidence', 'Seated sideways on a sculptural block with an elongated spine'], expressions: ['playful raised brow', 'wry almost-smile', 'warm radiant open smile'], phrases: ['GOOD TASTE, GREAT TIMING', 'WISDOM WEARS WELL', 'SEASONED WITH STYLE', 'THIS CHAPTER FITS PERFECTLY'], effects: ['Analog film grain and subtle light-leak color', 'Weathered letterpress grain with a modern polished focal point'] },
]

function choose(values: readonly string[], current: string, field: PromptField, random: () => number) {
  const fresh = values.filter((value) => value !== current && !isRecent(field, value))
  const alternatives = fresh.length ? fresh : values.filter((value) => value !== current)
  const pool = alternatives.length ? alternatives : values
  return pool[Math.min(pool.length - 1, Math.floor(random() * pool.length))]
}

function findWorld(brief: string, random: () => number) {
  const source = brief.toLowerCase()
  const scored = worlds.map((world) => ({ world, score: world.cues.filter((cue) => source.includes(cue)).length }))
  const best = Math.max(...scored.map((item) => item.score))
  const pool = best > 0 ? scored.filter((item) => item.score === best).map((item) => item.world) : worlds
  return pool[Math.min(pool.length - 1, Math.floor(random() * pool.length))]
}

export function applyCreativeDirection(current: PromptSelections, locked: ReadonlySet<PromptField> = new Set(), brief = '', random: () => number = Math.random) {
  const next = { ...current }
  const world = findWorld(brief, random)
  const fashion = world.fashion.map((name) => fashionLibrary.find((item) => item.name === name)).filter(Boolean).map((item) => describeFashion(item!))
  const typography = world.typography.map((name) => typographyLibrary.find((item) => item.name === name)).filter(Boolean).map((item) => describeTypography(item!))
  const palettes = world.palettes.map((name) => paletteLibrary.find((item) => item.name === name)).filter(Boolean).map((item) => describePalette(item!))
  const compositions = world.compositions.map((name) => compositionLibrary.find((item) => item.name === name)).filter(Boolean).map((item) => describeComposition(item!))
  const assign = (field: PromptField, values: readonly string[]) => {
    if (!locked.has(field) && values.length) next[field] = choose(values, current[field], field, random)
  }
  assign('fashion', fashion)
  assign('typography', typography)
  assign('palette', palettes)
  assign('composition', compositions)
  assign('artStyle', world.artStyles.filter((item) => artStyleLibrary.includes(item as typeof artStyleLibrary[number])))
  assign('pose', world.poses.filter((item) => poseLibrary.includes(item as typeof poseLibrary[number])))
  assign('expression', world.expressions.filter((item) => characterTraits.expressions.includes(item)))
  assign('phrase', world.phrases.filter((item) => phraseLibrary.includes(item as typeof phraseLibrary[number])))
  assign('effects', world.effects.filter((item) => effectLibrary.includes(item as typeof effectLibrary[number])))
  return next
}

export const creativeWorldCount = worlds.length
